import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* global css */}
        <link rel="stylesheet" href="/css/style.css" />
      </head>
      <body>
        {children}
      </body>
      <Script src="/js/lib.js" strategy="afterInteractive" />
    </html>
  );
}
